name: Deploy on Push to Main
run-name: ${{ github.actor }} essaie le GitHub workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
            eval "$(ssh-agent -s)"
            echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
      - name: Pull latest changes
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}<<EOF
            cd /var/www/html
            [ -d "/var/www/html/SAE501-Capollon" ] && rm -rf ./SAE501-Capollon
            git pull origin main
          EOF
      - name: Clean up
        run: |
          ssh-agent -k
          rm -rf ~/.ssh
